version: '3.8'

services:
  app-dev:
    container_name: bookingcare-be-dev
    image: bookingcare-be-dev
    env_file:
      - env/.env.development
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - bookingcare-be-dev
    depends_on:
      - db-dev

  db-dev:
    container_name: bookingcare-db-dev
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - env/.env.development
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - .docker/data/db-dev:/data/db
    restart: unless-stopped
    networks:
      - bookingcare-be-dev

  # pgadmin:
  #   container_name: pgadmin4
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #   ports:
  #     - ${PGADMIN_PORT}:80
  #   restart: unless-stopped
  #   depends_on:
  #     - db-dev

networks:
  bookingcare-be-dev:
    driver: bridge
